package cn.tust.dao;

import cn.tust.model.Teachers;
import cn.tust.model.TeachersExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TeachersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    long countByExample(TeachersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    int deleteByExample(TeachersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    int deleteByPrimaryKey(Integer tnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    int insert(Teachers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    int insertSelective(Teachers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    List<Teachers> selectByExample(TeachersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    Teachers selectByPrimaryKey(Integer tnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") Teachers record, @Param("example") TeachersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    int updateByExample(@Param("record") Teachers record, @Param("example") TeachersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    int updateByPrimaryKeySelective(Teachers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    int updateByPrimaryKey(Teachers record);
}