package cn.tust.model;

public class Courses {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.cNumber
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private Integer cnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.cName
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.cTeacher
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String cteacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.cWeek
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String cweek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.cPart
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String cpart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.cClassroom
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private Integer cclassroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.cCount
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private Integer ccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Courses(Integer cnumber, String cname, String cteacher, String cweek, String cpart, Integer cclassroom, Integer ccount) {
        this.cnumber = cnumber;
        this.cname = cname;
        this.cteacher = cteacher;
        this.cweek = cweek;
        this.cpart = cpart;
        this.cclassroom = cclassroom;
        this.ccount = ccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Courses() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.cNumber
     *
     * @return the value of courses.cNumber
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Integer getCnumber() {
        return cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.cNumber
     *
     * @param cnumber the value for courses.cNumber
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setCnumber(Integer cnumber) {
        this.cnumber = cnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.cName
     *
     * @return the value of courses.cName
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.cName
     *
     * @param cname the value for courses.cName
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.cTeacher
     *
     * @return the value of courses.cTeacher
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getCteacher() {
        return cteacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.cTeacher
     *
     * @param cteacher the value for courses.cTeacher
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setCteacher(String cteacher) {
        this.cteacher = cteacher == null ? null : cteacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.cWeek
     *
     * @return the value of courses.cWeek
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getCweek() {
        return cweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.cWeek
     *
     * @param cweek the value for courses.cWeek
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setCweek(String cweek) {
        this.cweek = cweek == null ? null : cweek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.cPart
     *
     * @return the value of courses.cPart
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getCpart() {
        return cpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.cPart
     *
     * @param cpart the value for courses.cPart
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setCpart(String cpart) {
        this.cpart = cpart == null ? null : cpart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.cClassroom
     *
     * @return the value of courses.cClassroom
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Integer getCclassroom() {
        return cclassroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.cClassroom
     *
     * @param cclassroom the value for courses.cClassroom
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setCclassroom(Integer cclassroom) {
        this.cclassroom = cclassroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.cCount
     *
     * @return the value of courses.cCount
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Integer getCcount() {
        return ccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.cCount
     *
     * @param ccount the value for courses.cCount
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setCcount(Integer ccount) {
        this.ccount = ccount;
    }
}