package cn.tust.model;

public class Students {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sNumber
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private Integer snumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sName
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sClass
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private Integer sclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sAge
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private Integer sage;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Students(Integer snumber, String sname, Integer sclass, Integer sage) {
        this.snumber = snumber;
        this.sname = sname;
        this.sclass = sclass;
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Students() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sNumber
     *
     * @return the value of students.sNumber
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Integer getSnumber() {
        return snumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sNumber
     *
     * @param snumber the value for students.sNumber
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setSnumber(Integer snumber) {
        this.snumber = snumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sName
     *
     * @return the value of students.sName
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sName
     *
     * @param sname the value for students.sName
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sClass
     *
     * @return the value of students.sClass
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Integer getSclass() {
        return sclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sClass
     *
     * @param sclass the value for students.sClass
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setSclass(Integer sclass) {
        this.sclass = sclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sAge
     *
     * @return the value of students.sAge
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sAge
     *
     * @param sage the value for students.sAge
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }
}