package cn.tust.model;

public class Teachers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.tNumber
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private Integer tnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.tName
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.tMajor
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String tmajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.tContact
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String tcontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.tClass
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String tclass;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Teachers(Integer tnumber, String tname, String tmajor, String tcontact, String tclass) {
        this.tnumber = tnumber;
        this.tname = tname;
        this.tmajor = tmajor;
        this.tcontact = tcontact;
        this.tclass = tclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Teachers() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.tNumber
     *
     * @return the value of teachers.tNumber
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Integer getTnumber() {
        return tnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.tNumber
     *
     * @param tnumber the value for teachers.tNumber
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setTnumber(Integer tnumber) {
        this.tnumber = tnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.tName
     *
     * @return the value of teachers.tName
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.tName
     *
     * @param tname the value for teachers.tName
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.tMajor
     *
     * @return the value of teachers.tMajor
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getTmajor() {
        return tmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.tMajor
     *
     * @param tmajor the value for teachers.tMajor
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setTmajor(String tmajor) {
        this.tmajor = tmajor == null ? null : tmajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.tContact
     *
     * @return the value of teachers.tContact
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getTcontact() {
        return tcontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.tContact
     *
     * @param tcontact the value for teachers.tContact
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setTcontact(String tcontact) {
        this.tcontact = tcontact == null ? null : tcontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.tClass
     *
     * @return the value of teachers.tClass
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getTclass() {
        return tclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.tClass
     *
     * @param tclass the value for teachers.tClass
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setTclass(String tclass) {
        this.tclass = tclass == null ? null : tclass.trim();
    }
}