package cn.tust.model;

public class Timetable extends TimetableKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column timetable.cScore
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private Integer cscore;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timetable
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Timetable(Integer snumber, Integer cnumber, Integer cscore) {
        super(snumber, cnumber);
        this.cscore = cscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table timetable
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Timetable() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column timetable.cScore
     *
     * @return the value of timetable.cScore
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Integer getCscore() {
        return cscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column timetable.cScore
     *
     * @param cscore the value for timetable.cScore
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setCscore(Integer cscore) {
        this.cscore = cscore;
    }
}