package cn.tust.model;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uName
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uPassword
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String upassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uType
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    private String utype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Users(String uname, String upassword, String utype) {
        this.uname = uname;
        this.upassword = upassword;
        this.utype = utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public Users() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uName
     *
     * @return the value of users.uName
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uName
     *
     * @param uname the value for users.uName
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uPassword
     *
     * @return the value of users.uPassword
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getUpassword() {
        return upassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uPassword
     *
     * @param upassword the value for users.uPassword
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setUpassword(String upassword) {
        this.upassword = upassword == null ? null : upassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uType
     *
     * @return the value of users.uType
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public String getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uType
     *
     * @param utype the value for users.uType
     * @mbg.generated Sun May 19 21:25:25 CST 2019
     */
    public void setUtype(String utype) {
        this.utype = utype == null ? null : utype.trim();
    }
}